### ISSUE TITLE
Create Script/TF for App Registration and Secret Creation

### ISSUE THREAD

**Issue by jofultz** [retaildevcrews/kube-oidc-proxy#1]
## Description
Terraform needs a Service Principal to create the AKS cluster.  We need to provide the subscription ID as an argument/var to the script and have Terraform create an App Registration with a client secret and assign contributor permissions.

The client secret should be stored in a variable for subsequent use by the rest of the script.  For dev purposes let's output to terminal window initially.

## Tasks

- [ ]  TF to create App Registration
- [ ] TF to create client secret, save the value to a variable, and output to the screen 
- [ ] TF to assign Contributor role to the App Registration

**Comment by jofultz** [comment]
Tagging Pri2 to indicate that this should happen when we focus on automation without an interactive user.

**Comment by evillgenius75** [comment]
@jofultz  This is definitely needed at some point for broader distribution, but for our customer case they pre-create all SPs in another system, by another team, and they just add the needed credentials at TF run time buy populating ENVARS that represent the TF VAR created. The reason is the TF Azure AD module requires super high permissions on Azure AD to be able to do a role assignment and they also don't allow users to create registrations.

Best for know to keep the TF SP creds needed as Variables. Maybe drop to Pri3. Take a look at how I approached it in the loki project: https://github.com/retaildevcrews/loki/tree/master/infrastructure/root#setup-the-tf-environment
