### ISSUE TITLE
Sprint0 Checklist

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/kube-oidc-proxy#3]
# Sprint0 Checklist

## Tooling
- [x] Setup/Configure Azure Subscriptions  (bartr/oidc)
- [ ] CI/CD Tooling 
- [ ] Work Item tracking Tooling (GitHub) 
- [x] Collaboration and Communication Tooling  (Teams)
- [x] Share user lists for Azure AD 
- [x] Share user lists for Source Control

## Planning
- [ ] Define success criteria 
- [x] Customer requirements
- [x] Customer Team identified
- [x] Microsoft Team identified 
- [x] Architecture Review Process

## Execution
- [ ] Sprint 0 plan (all stories and all features)
- [x] Sprint Plan (Weekly sprints)
- [x] Onsite plan (N/A)
- [x] Repo Policies 
- [ ] Branch Management (1 approver, SLA 12hrs)
- [x] Scrum ceremonies scheduled (Standups, Review/Retro: Fridays), Sprint M-Thr)

## Next Steps
- [ ] Create doc folder 
- [ ] Standup. Review/Retro, Planning meetings sent
- [ ] Update templates
- [ ] Update tags
- [ ] Define User Stories in repo
- [ ] Working Agreement (document)
